moviereviews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('review.urls')),
    path('accounts/', include('allauth.urls')),
]

review/urls.py
from . import views
from django.urls import path
from .views import CreateReview, UpdateReview, DeleteReview

urlpatterns = [
    path('', views.MovieList.as_view(), name='home'),
    path('review_detail/<slug:slug>/',
         views.ReviewDetail.as_view(), name='review_detail'),
    path('like/<slug:slug>', views.ReviewLike.as_view(), name='review_like'),
    path('create_review/', views.CreateReview.as_view(), name='create_review'),
    path('update_review/<slug:slug>',
         views.UpdateReview.as_view(), name='update_review'),
    path('delete_review/<slug:slug>/remove',
         views.DeleteReview.as_view(), name='delete_review'),
]

review/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

RATE_CHOICE = [
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
]


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Review(models.Model):
    title = models.CharField(max_length=75, unique=True)
    slug = models.SlugField(max_length=150, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='published_review')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    featured_image = CloudinaryField('image', default='placeholder')
    content = models.TextField(blank=False)
    excerpt = models.TextField(max_length=150, blank=False)
    status = models.IntegerField(choices=STATUS, default=1)
    likes = models.ManyToManyField(
        User, related_name='review_likes', blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    rating = models.IntegerField(choices=RATE_CHOICE, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    body = models.TextField()
    email = models.EmailField()
    name = models.CharField(max_length=80)
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Review, on_delete=models.CASCADE, related_name='comments')

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment {self.body} by {self.name}'

review/forms.py
from .models import Comment, Review
from django import forms
from django.forms import ModelForm
from django_summernote.widgets import SummernoteWidget


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={
                'required': True, 'placeholder': 'Write your comment here'}),
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'excerpt', 'category',
                  'rating', 'featured_image', 'content']
        widgets = {
            'content': SummernoteWidget(),
            'title': forms.TextInput(attrs={'placeholder': 'Title'}),
            'excerpt': forms.TextInput(attrs={
                'placeholder': 'Add a short description'}),
        }

review/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from .models import Review, Category
from .forms import CommentForm, ReviewForm
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.contrib.messages.views import SuccessMessageMixin


class MovieList(generic.ListView):
    model = Review
    queryset = Review.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 8


class ReviewDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Review.objects.filter(status=1)
        review = get_object_or_404(queryset, slug=slug)
        comments = review.comments.filter(approved=True).order_by('created_on')
        category = True
        rating = True
        liked = False
        if review.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            'review_detail.html',
            {
                'review': review,
                'comments': comments,
                'commented': False,
                'liked': liked,
                'rating': rating,
                'category': category,
                'comment_form': CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Review.objects.filter(status=1)
        review = get_object_or_404(queryset, slug=slug)
        comments = review.comments.filter(approved=True).order_by('created_on')
        liked = False
        if review.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = review
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            'review_detail.html',
            {
                'review': review,
                'comments': comments,
                'commented': True,
                'liked': liked,
                'comment_form': CommentForm,
            },
        )

# Create, update & delete review


def createreview(request):
    return render(request, 'create_review.html', {})


class CreateReview(CreateView):

    model = Review
    template_name = 'create_review.html'
    form_class = ReviewForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.pk
        form.instance.slug = slugify(form.instance.title)
        success_message = "Success! Your review has been created."
        messages.add_message(self.request, messages.SUCCESS, success_message)
        return super().form_valid(form)


class UpdateReview(UpdateView):

    model = Review
    template_name = 'update_review.html'
    form_class = ReviewForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.pk
        form.instance.slug = slugify(form.instance.title)
        success_message = "Success! Your review has been updated."
        messages.add_message(self.request, messages.SUCCESS, success_message)
        return super().form_valid(form)


class DeleteReview(SuccessMessageMixin, DeleteView):

    model = Review
    template_name = 'delete_review.html'
    success_url = reverse_lazy('home')
    success_message = "Your review has been deleted"

    def delete_review(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteReview, self).delete(request, *args, **kwargs)


# Like

class ReviewLike(View):

    def post(self, request, slug, *args, **kwargs):
        review = get_object_or_404(Review, slug=slug)

        if review.likes.filter(id=request.user.id).exists():
            review.likes.remove(request.user)
        else:
            review.likes.add(request.user)

        return HttpResponseRedirect(reverse('review_detail', args=[slug]))

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"/>
    
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>

    <!-- Favicon -->
    <link rel="icon" type="image" sizes="16x16" href="https://img.icons8.com/ios-filled/50/film-reel--v1.png"/>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/69f27fd7ee.js" crossorigin="anonymous"></script>

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,300&display=swap" rel="stylesheet"/>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>Movie Reviews</title>
  </head>

  <body class="page">
    <!-- Navigation -->
    <nav id="navbar" class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Movie Reviews</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse nav justify-content-end" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-link active" aria-current="page" href="{% url 'create_review' %}">Review Movie</a>
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
            <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

    <!-- Alert messages -->
    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
            {{ message | safe }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

    <!-- Main Content -->
    <main>
    {% block content %} {% endblock content %}
    </main>
    <!-- Footer -->
    <footer class="" id="footer">
        <ul id="social-media">
            <li>
                <a id="facebook" href="https://facebook.com" rel="noopener" aria-label="Visit us on Facebook (opens in a new tab)" target="_blank"><i class="fa-brands fa-facebook"></i></a>
            </li>
            <li>
                <a id="twitter" href="https://twitter.com" rel="noopener" aria-label="Visit us on Twitter (opens in a new tab)" target="_blank"><i class="fa-brands fa-twitter"></i></a>
            </li>
            <li>
                <a id="youtube" href="https://youtube.com" rel="noopener" aria-label="Visit us on Youtube (opens in a new tab)" target="_blank"><i class="fa-brands fa-youtube"></i></a>
            </li>
            <li>
                <a id="instagram" href="https://instagram.com" rel="noopener" aria-label="Visit us on Instagram (opens in a new tab)" target="_blank"><i class="fa-brands fa-instagram"></i></a>
            </li>
        </ul>
    </footer>

    <script>
      setTimeout(function () {
        let messages = document.getElementById("msg");
        let alert = new bootstrap.Alert(messages);
        alert.close();
      }, 2500);
    </script>
  </body>
</html>

templates/contact-us.html
<div class="col-lg-7">
    <div class="contact">
        <!-- Contact form -->
        <div class="row">
            <div class="col-md-6 mb-4">
                <input type="text" class="form-control" name="name" placeholder="Name" id="name" required>
            </div>
            <div class="col-md-6  mb-4">
                <input type="email" class="form-control" name="email" placeholder="Email Address" id="email" required>
            </div>

            <div class="col-md-12 mb-4">
                <input type="text" name="Topic" class="form-control" placeholder="Topic" required="required">
            </div>
            <div class="col-md-12 mb-4">
                <textarea rows="8" class="form-control" name="message" placeholder="Message" id="message"
                    required></textarea>
            </div>

            <div class="col-md-12 mb-4">
                <button type="submit" class="btn btn-primary" id="sendMessageButton" style="width: 100%;">Send</button>
            </div>
        </div>
    </div>
</div>

templates/create-review.html
<form>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 col-lg-6">
                <div class="card-body">
                    <div class="card-body text-center">
                        <h3 class="mb-4 text-uppercase text-center">Create Review</h3>
                        <!-- Post create form -->
                        <form method="post">

                            <div class="mb-3">
                                Test
                            </div>
                            <button class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

templates/create_review.html
{% extends "base.html" %} {% block content %} 

{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<!-- Create Review -->
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="card text-center col-12 col-md-6 col-lg-6">
            <strong>
            <h3 class="my-3 text-uppercase text-center">Create Review</h3>
            <!-- Post Create form -->
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary my-2">Submit</button>
            </strong>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/delete_review.html
{% extends "base.html" %} {% block content %}

{% load crispy_forms_tags %}
{% if user.is_authenticated %}
{% if user.id == review.author.id %}
<!-- Delete Review -->
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="card text-center col-12 col-md-6 col-lg-6">
            <strong>
                <h3 class="my-3 text-uppercase text-center">Delete: {{ review.title }}</h3>
                <!-- Post delete form -->
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Are you sure you want to delete this review?</p>
                    <button class="btn btn-danger my-2">Delete Review</button>
            </strong>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %} {% block content %}


<div class="container my-5">
    <div class="card text-center">
        <h2>Welcome to Movie Reviews!</h2>
        <p class="mt-2">Welcome! This is a site where you can review, read movie reviews, interact with people & share
            your opinions for others to see.</p>
        <p>Enjoy your stay!</p>
    </div>
</div>

<!-- Review content -->

<div class="container container-table">
    <div class="row">
        {% for review in review_list %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div id="card-content" class="card my-2">
                {% if "placeholder" in review.featured_image.url %}
                <img src="https://images.unsplash.com/photo-1616530940355-351fabd9524b?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="card-img-top" alt="image of different movie posters">
                {% else %}
                <img class="card-img-top" src="{{ review.featured_image.url }}" alt="image of the movie"/>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ review.title }}</h5>
                    <h6 class="card-text my-3">{{ review.author }}</h6>
                    <p class="card-text">{{ review.category }}</p>
                    <p class="card-text">{{ review.excerpt }}</p>
                    <hr>
                        <i class="fa-regular fa-thumbs-up"></i>{{ review.number_of_likes }}
                        <i class="fas fa-star" id="star-rating"></i>
                        <label class="text-primary">{{ review.rating }}</label>
                    <hr>
                    <a href="{% url 'review_detail' review.slug %}" class="btn view">Read Review</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Page navigation -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo; Previous page</a>
            </li>
            {% endif %} {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next page &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

templates/mfa/authenticate.html
{% extends "mfa/base_entrance.html" %}
{% load i18n %}
{% load allauth %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    {% url 'mfa_authenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" %}
                {% trans "Sign In" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/base_entrance.html
{% extends "allauth/layouts/entrance.html" %}

templates/mfa/base_manage.html
{% extends "allauth/layouts/manage.html" %}

templates/mfa/index.html
{% extends "mfa/base_manage.html" %}
{% load allauth %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    {% element h1 tags="mfa,index" %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    {% element panel %}
        {% slot title %}
            {% translate "Authenticator App" %}
        {% endslot %}
        {% slot body %}
            {% if authenticators.totp %}
                <p>{% translate "Authentication using an authenticator app is active." %}</p>
            {% else %}
                <p>{% translate "An authenticator app is not active." %}</p>
            {% endif %}
        {% endslot %}
        {% slot actions %}
            {% url 'mfa_deactivate_totp' as deactivate_url %}
            {% url 'mfa_activate_totp' as activate_url %}
            {% if authenticators.totp %}
                {% element button href=deactivate_url tags="danger,delete,panel" %}
                    {% translate "Deactivate" %}
                {% endelement %}
            {% else %}
                {% element button href=activate_url tags="panel" %}
                    {% translate "Activate" %}
                {% endelement %}
            {% endif %}
        {% endslot %}
    {% endelement %}
    {% with total_count=authenticators.recovery_codes.generate_codes|length unused_count=authenticators.recovery_codes.get_unused_codes|length %}
        {% element panel %}
            {% slot title %}
                {% translate "Recovery Codes" %}
            {% endslot %}
            {% slot body %}
                {% if authenticators.recovery_codes %}
                    <p>
                        {% blocktranslate count unused_count=unused_count %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
                    </p>
                {% else %}
                    <p>{% translate "No recovery codes set up." %}</p>
                {% endif %}
            {% endslot %}
            {% if is_mfa_enabled %}
                {% if authenticators.recovery_codes %}
                    {% if unused_count > 0 %}
                        {% slot actions %}
                            {% url 'mfa_view_recovery_codes' as view_url %}
                            {% element button href=view_url tags="panel" %}
                                {% translate "View" %}
                            {% endelement %}
                        {% endslot %}
                        {% slot actions %}
                            {% url 'mfa_download_recovery_codes' as download_url %}
                            {% element button href=download_url tags="secondary,panel" %}
                                {% translate "Download" %}
                            {% endelement %}
                        {% endslot %}
                    {% endif %}
                {% endif %}
                {% slot actions %}
                    {% url 'mfa_generate_recovery_codes' as generate_url %}
                    {% element button href=generate_url tags="secondary,panel" %}
                        {% translate "Generate" %}
                    {% endelement %}
                {% endslot %}
            {% endif %}
        {% endelement %}
    {% endwith %}
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        {% translate "Recovery Codes" %}
    {% endelement %}
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account.{% endblocktranslate %}
        {% if unused_code_count %}
            {% blocktranslate %}This action will invalidate your existing codes.{% endblocktranslate %}
        {% endif %}
        {% blocktranslate %}Are you sure?{% endblocktranslate %}
    </p>
    {% url 'mfa_generate_recovery_codes' as action_url %}
    {% element form method="post" action=action_url no_visible_fields=True %}
        {% slot body %}
            {% csrf_token %}
            {{ form.as_p }}
        {% endslot %}
        {% slot actions %}
            {% setvar tags %}
                {% if unused_code_count %}
                    danger
                {% else %}
                {% endif %}
            {% endsetvar %}
            {% element button type="submit" tags=tags %}
                {% trans "Generate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        {% translate "Recovery Codes" %}
    {% endelement %}
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% element field id="recovery_codes" type="textarea" disabled="disabled" rows=unused_codes|length readonly=True %}
        {% slot label %}
            {% translate "Unused codes" %}
        {% endslot %}
        {% comment %} djlint:off {% endcomment %}
    {% slot value %}{% for code in unused_codes %}{% if forloop.counter0 %}
{% endif %}{{ code }}{% endfor %}{% endslot %}
{% comment %} djlint:on {% endcomment %}
{% endelement %}
{% if unused_codes %}
{% url 'mfa_download_recovery_codes' as download_url %}
{% element button href=download_url %}
{% translate "Download codes" %}
{% endelement %}
{% endif %}
{% url 'mfa_generate_recovery_codes' as generate_url %}
{% element button href=generate_url %}
{% translate "Generate new codes" %}
{% endelement %}
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load allauth i18n %}
{% block head_title %}
    {% translate "Activate Authenticator App" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% translate "Activate Authenticator App" %}
    {% endelement %}
    <p>
        {% blocktranslate %}To protect your account with two-factor authentication, scan the QR code below with your authenticator app. Then, input the verification code generated by the app below.{% endblocktranslate %}
    </p>
    {% url 'mfa_activate_totp' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% element img src=totp_svg_data_uri alt=form.secret tags="mfa,totp,qr" %}
            {% endelement %}
            {% csrf_token %}
            {% element field type="text" value=form.secret disabled="disabled" %}
                {% slot label %}
                    {% translate "Authenticator secret" %}
                {% endslot %}
                {% slot help_text %}
                    {% translate "You can store this secret and use it to reinstall your authenticator app at a later time." %}
                {% endslot %}
            {% endelement %}
            {% element fields form=form %}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button  type="submit" %}
                {% trans "Activate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/totp/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% load allauth %}
{% block head_title %}
    {% trans "Deactivate Authenticator App" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Deactivate Authenticator App" %}
    {% endelement %}
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    {% url 'mfa_deactivate_totp' as action_url %}
    {% element form form=form method="post" action=action_url no_visible_fields=True %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form %}
                {{ form.as_p }}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button tags="danger,delete" type="submit" %}
                {% trans "Deactivate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/update_review.html
{% extends "base.html" %} {% block content %}

{% load crispy_forms_tags %}
{% if user.is_authenticated %}
{% if user.id == review.author.id %}
<!-- Update Review -->
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="card text-center col-12 col-md-6 col-lg-6">
            <strong>
                <h3 class="my-3 text-uppercase text-center">Update Review</h3>
                <!-- Post Update form -->
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-success my-2">Update</button>
            </strong>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endif %}
{% endblock %}